### ISSUE TITLE
Adding AppleCore-mc1.12-2.2.2.jar to the buildpath in Eclipse crashes the game.

### ISSUE THREAD

**Issue by Leowbattle** [squeek502/AppleCore#106]
> Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
[09:22:14] [main/INFO] [GradleStart]: Extra: []
[09:22:14] [main/INFO] [GradleStart]: Found and added coremod: squeek.applecore.AppleCore
[09:22:14] [main/INFO] [GradleStart]: Running with arguments: [--userProperties, {}, --assetsDir, /Users/leobattle/.gradle/caches/minecraft/assets, --assetIndex, 1.12, --accessToken{REDACTED}, --version, 1.12, --tweakClass, net.minecraftforge.fml.common.launcher.FMLTweaker, --tweakClass, net.minecraftforge.gradle.tweakers.CoremodTweaker]
[09:22:14] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[09:22:14] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[09:22:14] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.gradle.tweakers.CoremodTweaker
[09:22:14] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[09:22:14] [main/INFO] [FML]: Forge Mod Loader version 14.21.1.2443 for Minecraft 1.12 loading
[09:22:14] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_131, running on Mac OS X:x86_64:10.13.1, installed at /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre
[09:22:14] [main/INFO] [FML]: Managed to load a deobfuscated Minecraft name- we are in a deobfuscated environment. Skipping runtime deobfuscation
[09:22:14] [main/INFO] [FML]: Ignoring missing certificate for coremod FMLCorePlugin (net.minecraftforge.fml.relauncher.FMLCorePlugin), we are in deobf and it's a forge core plugin
[09:22:14] [main/INFO] [FML]: Ignoring missing certificate for coremod FMLForgePlugin (net.minecraftforge.classloading.FMLForgePlugin), we are in deobf and it's a forge core plugin
[09:22:14] [main/INFO] [FML]: Found a command line coremod : squeek.applecore.AppleCore
[09:22:14] [main/INFO] [FML]: Ignoring missing certificate for coremod AppleCore (squeek.applecore.AppleCore), as this is a probably dev workspace
[09:22:14] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in AppleCore-mc1.12-2.2.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[09:22:14] [main/WARN] [FML]: The coremod AppleCore (squeek.applecore.AppleCore) is not signed!
[09:22:14] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in CodeChickenLib-1.12-3.1.3.313-universal.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[09:22:14] [main/ERROR] [FML]: Coremod codechicken.lib.asm.CCLCorePlugin: Unable to class load the plugin java.lang.ClassNotFoundException: codechicken.lib.asm.CCLCorePlugin
[09:22:14] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.gradle.tweakers.CoremodTweaker
[09:22:14] [main/INFO] [GradleStart]: Injecting location in coremod net.minecraftforge.fml.relauncher.FMLCorePlugin
[09:22:14] [main/INFO] [GradleStart]: Injecting location in coremod net.minecraftforge.classloading.FMLForgePlugin
[09:22:14] [main/INFO] [GradleStart]: Injecting location in coremod squeek.applecore.AppleCore
[09:22:14] [main/INFO] [GradleStart]: Injecting location in coremod squeek.applecore.AppleCore
[09:22:14] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[09:22:14] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[09:22:14] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.gradle.tweakers.AccessTransformerTweaker
[09:22:14] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[09:22:14] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[09:22:14] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[09:22:15] [main/ERROR] [FML]: FML appears to be missing any signature data. This is not a good thing
[09:22:15] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[09:22:15] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[09:22:16] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.gradle.tweakers.AccessTransformerTweaker
[09:22:16] [main/INFO] [GradleStart]: Remapping AccessTransformer rules...
[09:22:16] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[09:22:16] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[09:22:16] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[09:22:16] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[09:22:16] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[09:22:16] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/client/GuiIngameForge
	at net.minecraft.client.main.Main.main(Main.java:42) ~[Main.class:?]
	... 12 more
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.client.GuiIngameForge
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
	at net.minecraft.client.main.Main.main(Main.java:42) ~[Main.class:?]
	... 12 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer squeek.applecore.asm.TransformerModuleHandler@15dc339f from coremod AppleCore
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:262) ~[forgeSrc-1.12-14.21.1.2443.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
	at net.minecraft.client.main.Main.main(Main.java:42) ~[Main.class:?]
	... 12 more
Caused by: java.lang.RuntimeException: GuiIngameForge: expected instruction pattern not found
	at squeek.applecore.asm.module.ModuleHungerHUD.transform(ModuleHungerHUD.java:40) ~[AppleCore-mc1.12-2.2.2.jar:?]
	at squeek.applecore.asm.TransformerModuleHandler.transform(TransformerModuleHandler.java:42) ~[AppleCore-mc1.12-2.2.2.jar:?]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258) ~[forgeSrc-1.12-14.21.1.2443.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
	at net.minecraft.client.main.Main.main(Main.java:42) ~[Main.class:?]
	... 12 more
Exception in thread "main" [09:22:16] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.reflect.InvocationTargetException
[09:22:16] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:22:16] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[09:22:16] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09:22:16] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[09:22:16] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
[09:22:16] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at GradleStart.main(GradleStart.java:26)
[09:22:16] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[09:22:16] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[09:22:16] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[09:22:16] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.Runtime.exit(Runtime.java:107)
[09:22:16] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.System.exit(System.java:971)
[09:22:16] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[09:22:16] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[09:22:16] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 6 more

**Comment by Leowbattle** [comment]
It also only happens when AppleSkin is installed at the same time or I use a class from AppleCore.

**Comment by NightmareTwilight** [comment]
I have the same problem, though it's for 'Ticking player
java.lang.NoSuchMethodError: net.minecraft.util.FoodStats.func_75116_a()I'
every time I reference a function/class of applecore in eclipse. This is for 3.2.0, but also happens in 3.1.9. Works fine after I build a file, only crashes in dev-environment.

> ---- Minecraft Crash Report ----
> // Hey, that tickles! Hehehe!
> 
> Time: 8/9/19 3:30 PM
> Description: Ticking player
> 
> java.lang.NoSuchMethodError: net.minecraft.util.FoodStats.func_75116_a()I
> 	at squeek.applecore.asm.Hooks.onAppleCoreFoodStatsUpdate(Hooks.java:63)
> 	at net.minecraft.util.FoodStats.onUpdate(FoodStats.java:42)
> 	at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:289)
> 	at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:423)
> 	at net.minecraft.network.NetHandlerPlayServer.update(NetHandlerPlayServer.java:185)
> 	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.update(NetworkDispatcher.java:212)
> 	at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:307)
> 	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:197)
> 	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:865)
> 	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:743)
> 	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:192)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:592)
> 	at java.lang.Thread.run(Unknown Source)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Server thread
> Stacktrace:
> 	at squeek.applecore.asm.Hooks.onAppleCoreFoodStatsUpdate(Hooks.java:63)
> 	at net.minecraft.util.FoodStats.onUpdate(FoodStats.java:42)
> 	at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:289)
> 
> -- Player being ticked --
> Details:
> 	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
> 	Entity ID: 349
> 	Entity Name: Player888
> 	Entity's Exact location: -177.23, 70.00, 120.86
> 	Entity's Block location: World: (-178,70,120), Chunk: (at 14,4,8 in -12,7; contains blocks -192,0,112 to -177,255,127), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
> 	Entity's Momentum: 0.00, -0.08, 0.00
> 	Entity's Passengers: []
> 	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
> Stacktrace:
> 	at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:423)
> 	at net.minecraft.network.NetHandlerPlayServer.update(NetHandlerPlayServer.java:185)
> 	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.update(NetworkDispatcher.java:212)
> 	at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:307)
> 
> -- Ticking connection --
> Details:
> 	Connection: net.minecraft.network.NetworkManager@5ace71d5
> Stacktrace:
> 	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:197)
> 	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:865)
> 	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:743)
> 	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:192)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:592)
> 	at java.lang.Thread.run(Unknown Source)
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.12.2
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 1.8.0_201, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 266761568 bytes (254 MB) / 689963008 bytes (658 MB) up to 3817865216 bytes (3641 MB)
> 	JVM Flags: 1 total; -Xmx4096m
> 	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
> 	FML: MCP 9.42 Powered by Forge 14.23.5.2838 9 mods loaded, 9 mods active
> 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
> 
> 	| State  | ID              | Version      | Source                           | Signature |
> 	|:------ |:--------------- |:------------ |:-------------------------------- |:--------- |
> 	| LCHIJA | minecraft       | 1.12.2       | minecraft.jar                    | None      |
> 	| LCHIJA | mcp             | 9.42         | minecraft.jar                    | None      |
> 	| LCHIJA | FML             | 8.0.99.99    | forgeSrc-1.12.2-14.23.5.2838.jar | None      |
> 	| LCHIJA | forge           | 14.23.5.2838 | forgeSrc-1.12.2-14.23.5.2838.jar | None      |
> 	| LCHIJA | skilltree       | 1.2.3.0      | SkillTree-1.2.3.0.jar            | None      |
> 	| LCHIJA | applecore       | 3.2.0        | AppleCore-mc1.12.2-3.2.0.jar     | None      |
> 	| LCHIJA | simplerpgskills | 0.5.0        | bin                              | None      |
> 	| LCHIJA | classicbar      | @VERSION@    | classicbar-0.3.4c.jar            | None      |
> 	| LCHIJA | testdummy       | 1.12         | MmmMmmMmmMmm-1.12-1.14.jar       | None      |
> 
> 	Loaded coremods (and transformers): 
> AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
>   squeek.applecore.asm.TransformerModuleHandler
> 	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
> 	Profiler Position: N/A (disabled)
> 	Player Count: 1 / 8; [EntityPlayerMP['Player888'/349, l='testing1', x=-177.23, y=70.00, z=120.86]]
> 	Type: Integrated Server (map_client.txt)
> 	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by democat3457** [comment]
Can reproduce the above crash with v3.4.0
```
Time: 12/24/21 2:52 AM
Description: Ticking player

java.lang.NoSuchMethodError: net.minecraft.util.FoodStats.func_75116_a()I
        at squeek.applecore.asm.Hooks.onAppleCoreFoodStatsUpdate(Hooks.java:63)
        at net.minecraft.util.FoodStats.onUpdate(FoodStats.java:42)
        at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:289)
        at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:423)
        at net.minecraft.network.NetHandlerPlayServer.update(NetHandlerPlayServer.java:185)
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.update(NetworkDispatcher.java:212)
        at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:307)
        at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:197)
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:865)
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:743)
        at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:192)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:592)
        at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
        at squeek.applecore.asm.Hooks.onAppleCoreFoodStatsUpdate(Hooks.java:63)
        at net.minecraft.util.FoodStats.onUpdate(FoodStats.java:42)
        at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:289)

-- Player being ticked --
Details:
        Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
        Entity ID: 582
        Entity Name: Player627
        Entity's Exact location: 212.50, 64.00, 154.50
        Entity's Block location: World: (212,64,154), Chunk: (at 4,4,10 in 13,9; contains blocks 208,0,144 to 223,255,159), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
        Entity's Momentum: 0.00, -0.08, 0.00
        Entity's Passengers: []
        Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
        at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:423)
        at net.minecraft.network.NetHandlerPlayServer.update(NetHandlerPlayServer.java:185)
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.update(NetworkDispatcher.java:212)
        at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:307)

-- Ticking connection --
Details:
        Connection: net.minecraft.network.NetworkManager@69a51434
Stacktrace:
        at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:197)
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:865)
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:743)
        at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:192)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:592)
        at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
        Minecraft Version: 1.12.2
        Operating System: Mac OS X (x86_64) version 10.15.6
        Java Version: 1.8.0_221, Oracle Corporation
        Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 606154240 bytes (578 MB) / 1003487232 bytes (957 MB) up to 1908932608 bytes (1820 MB)
        JVM Flags: 0 total; 
        IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
        FML: MCP 9.42 Powered by Forge 14.23.5.2847 12 mods loaded, 12 mods active
        States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

        | State  | ID            | Version      | Source                                          | Signature |
        |:------ |:------------- |:------------ |:----------------------------------------------- |:--------- |
        | LCHIJA | minecraft     | 1.12.2       | minecraft.jar                                   | None      |
        | LCHIJA | mcp           | 9.42         | minecraft.jar                                   | None      |
        | LCHIJA | FML           | 8.0.99.99    | forgeSrc-1.12.2-14.23.5.2847-PROJECT(Quark).jar | None      |
        | LCHIJA | forge         | 14.23.5.2847 | forgeSrc-1.12.2-14.23.5.2847-PROJECT(Quark).jar | None      |
        | LCHIJA | baubles       | 1.5.2        | Baubles-1.12-1.5.2.jar                          | None      |
        | LCHIJA | jei           | 4.15.0.285   | jei_1.12.2-4.15.0.285.jar                       | None      |
        | LCHIJA | quark         | r1.6-183     | Quark-r1.6-183.jar                              | None      |
        | LCHIJA | autoreglib    | 1.3-32       | AutoRegLib-1.3-32.33.jar                        | None      |
        | LCHIJA | applecore     | 3.4.0        | AppleCore-mc1.12.2-3.4.0.jar                    | None      |
        | LCHIJA | appleskin     | 1.0.14       | AppleSkin-mc1.12-1.0.14.jar                     | None      |
        | LCHIJA | betterhud     | 1.4.4        | betterhud-1.12.2-1.4.4.jar                      | None      |
        | LCHIJA | quarkoddities | 1            | QuarkOddities.jar                               | None      |

        Loaded coremods (and transformers): 
Quark Plugin (Quark-r1.6-183.jar)
  vazkii.quark.base.asm.ClassTransformer
AppleCore (AppleCore-mc1.12.2-3.4.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
        GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
        Profiler Position: N/A (disabled)
        Player Count: 1 / 8; [EntityPlayerMP['Player627'/582, l='hud compatt', x=212.50, y=64.00, z=154.50]]
        Type: Integrated Server (map_client.txt)
        Is Modded: Definitely; Client brand changed to 'fml,forge'
```
