### ISSUE TITLE
[Crash] when opening game (unable to launch)

### ISSUE THREAD

**Issue by winsrp** [squeek502/AppleCore#127]
applecore 3.1.3
forge 2655

[10:57:47] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/entity/player/EntityPlayer
	at net.minecraft.client.main.Main.main(SourceFile:38) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.entity.player.EntityPlayer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_171]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_171]
	at net.minecraft.client.main.Main.main(SourceFile:38) ~[Main.class:?]
	... 6 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer squeek.applecore.asm.TransformerModuleHandler@68577ba8 from coremod AppleCore
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:262) ~[forge-1.12.2-14.23.3.2655.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_171]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_171]
	at net.minecraft.client.main.Main.main(SourceFile:38) ~[Main.class:?]
	... 6 more
Caused by: java.lang.NullPointerException
	at squeek.applecore.asm.module.ModulePeacefulRegen.addPeacefulRegenHook(ModulePeacefulRegen.java:45) ~[AppleCore-mc1.12.2-3.1.3.jar:?]
	at squeek.applecore.asm.module.ModulePeacefulRegen.transform(ModulePeacefulRegen.java:29) ~[AppleCore-mc1.12.2-3.1.3.jar:?]
	at squeek.applecore.asm.TransformerModuleHandler.transform(TransformerModuleHandler.java:41) ~[AppleCore-mc1.12.2-3.1.3.jar:?]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258) ~[forge-1.12.2-14.23.3.2655.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_171]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_171]
	at net.minecraft.client.main.Main.main(SourceFile:38) ~[Main.class:?]
	... 6 more
[10:57:47] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[10:57:47] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[10:57:47] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[10:57:47] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[10:57:47] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[10:57:47] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[10:57:47] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by squeek502** [comment]
Looks like a conflict with another core mod. Which other mods do you have installed?

**Comment by winsrp** [comment]
never mind found the issue, i had another version apple core mod, with another name on the same folder XD
