### ISSUE TITLE
Crash upon entering world (1.12.2)

### ISSUE THREAD

**Issue by warrenher** [squeek502/AppleCore#137]
After adding a few mods (specifically: _RebornCore-1.12.2-3.13.8.430, future-mc-0.1.1, essentialfeatures-2.2.0, gregtech-1.12.2-1.6.3.358, TechReborn-1.12.2-2.21.2.960-universal, jei_1.12.2-4.15.0.269, WaterPower-1.12-0.5.8, LittleTiles_v1.5.0-pre127_mc1.12.2, CreativeCore_v1.9.40_mc1.12.2, u_team_core-1.12.2-2.2.4.94, useful_railroads-1.12.2-0.1.1.4-SNAPSHOT_) I suddenly am unable to enter my world.
This is the error I am getting each time I enter my world:
`java.lang.RuntimeException: FoodStats has a null player field (this field is added by AppleCore at runtime) on player '<unknown>' (class = us.bemrose.mc.pitweaks.FoodCapTweak$TweakFoodStats). This likely means that some mod has overloaded FoodStats, which is incompatible with AppleCore.
    at squeek.applecore.asm.Hooks.verifyFoodStats(Hooks.java:53)
    at squeek.applecore.asm.Hooks.needFood(Hooks.java:270)
    at net.minecraft.util.FoodStats.needFood(SourceFile)
    at com.buuz135.industrial.proxy.event.MeatFeederTickHandler.onTick(MeatFeederTickHandler.java:47)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_3116_MeatFeederTickHandler_onTick_LivingUpdateEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:575)
    at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2095)
    at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:234)
    at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:382)
    at net.minecraft.network.NetHandlerPlayServer.update(NetHandlerPlayServer.java:173)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.update(NetworkDispatcher.java:209)
    at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:285)
    at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:180)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:790)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:256)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)`

According to VanillaFix, the cause is either AppleCore or Industrial Foregoing, which I doubt as those mods were initially included in the modpack I built upon, you could say. I am unaware of any of these mods I recently added apparently overloading the FoodStats.

**Comment by squeek502** [comment]
Update CplPibald's Tweaks. See https://github.com/squeek502/AppleCore/issues/134#issuecomment-473753230
