### ISSUE TITLE
Help With java.lang.AbstractMethodError

### ISSUE THREAD

**Issue by Zenvian** [squeek502/AppleCore#156]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  GSHooksLoader (GalaxySpace-1.12.2-2.0.16.jar)
  LoadingPlugin (replaymod-1.12.2-2.2.0-b7.jar)
  SteveKunGLibPlugin (SteveKunG's-Lib-1.12.2-1.1.9.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  XaeroMinimapPlugin (Xaeros_Minimap_21.4.4_Forge_1.12.jar)
  AppleCore (AppleCore-mc1.12.2-3.4.0.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 6/6/21 9:46 PM
Description: Initializing game

java.lang.AbstractMethodError
	at squeek.applecore.api_impl.AppleCoreAccessorMutatorImpl.getUnmodifiedFoodValues(AppleCoreAccessorMutatorImpl.java:92)
	at squeek.applecore.api_impl.AppleCoreAccessorMutatorImpl.isFood(AppleCoreAccessorMutatorImpl.java:41)
	at iguanaman.hungeroverhaul.module.event.HungerOverhaulEventHook.renderTooltips(HungerOverhaulEventHook.java:634)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_735_HungerOverhaulEventHook_renderTooltips_ItemTooltipEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:358)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:889)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:576)
	at net.minecraft.client.Minecraft$$Lambda$729/193693238.apply(Unknown Source)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at net.minecraft.client.Minecraft$$Lambda$738/1420791409.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:590)
	at net.minecraftforge.fml.client.FMLClientHandler.reloadSearchTrees(FMLClientHandler.java:1086)
	at net.minecraftforge.fml.common.FMLCommonHandler.reloadSearchTrees(FMLCommonHandler.java:778)
	at net.minecraftforge.common.ForgeModContainer.mappingChanged(ForgeModContainer.java:589)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at net.minecraftforge.fml.common.Loader.fireRemapEvent(Loader.java:916)
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:259)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:758)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at squeek.applecore.api_impl.AppleCoreAccessorMutatorImpl.getUnmodifiedFoodValues(AppleCoreAccessorMutatorImpl.java:92)
	at squeek.applecore.api_impl.AppleCoreAccessorMutatorImpl.isFood(AppleCoreAccessorMutatorImpl.java:41)
	at iguanaman.hungeroverhaul.module.event.HungerOverhaulEventHook.renderTooltips(HungerOverhaulEventHook.java:634)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_735_HungerOverhaulEventHook_renderTooltips_ItemTooltipEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:358)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:889)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:576)
	at net.minecraft.client.Minecraft$$Lambda$729/193693238.apply(Unknown Source)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at net.minecraft.client.Minecraft$$Lambda$738/1420791409.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:590)
	at net.minecraftforge.fml.client.FMLClientHandler.reloadSearchTrees(FMLClientHandler.java:1086)
	at net.minecraftforge.fml.common.FMLCommonHandler.reloadSearchTrees(FMLCommonHandler.java:778)
	at net.minecraftforge.common.ForgeModContainer.mappingChanged(ForgeModContainer.java:589)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at net.minecraftforge.fml.common.Loader.fireRemapEvent(Loader.java:916)
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:259)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:758)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 315038728 bytes (300 MB) / 1811939328 bytes (1728 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 44 mods loaded, 44 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version                  | Source                                        | Signature                                |
	|:------ |:------------------- |:------------------------ |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2                   | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                 | 9.42                     | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                 | 8.0.99.99                | forge-1.12.2-14.23.5.2855.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge               | 14.23.5.2855             | forge-1.12.2-14.23.5.2855.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | micdoodlecore       |                          | minecraft.jar                                 | None                                     |
	| LCHIJA | xaerominimap_core   | 1.12.2-1.0               | minecraft.jar                                 | None                                     |
	| LCHIJA | replaymod           | 1.12.2-2.2.0-b7          | replaymod-1.12.2-2.2.0-b7.jar                 | None                                     |
	| LCHIJA | aether_legacy       | 1.5.3.2                  | aether-1.12.2-v1.5.3.2.jar                    | None                                     |
	| LCHIJA | applecore           | 3.4.0                    | AppleCore-mc1.12.2-3.4.0.jar                  | None                                     |
	| LCHIJA | artemislib          | 1.0.6                    | ArtemisLib-1.12.2-v1.0.6.jar                  | None                                     |
	| LCHIJA | mantle              | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                      | None                                     |
	| LCHIJA | jei                 | 4.16.1.301               | jei_1.12.2-4.16.1.301.jar                     | None                                     |
	| LCHIJA | twilightforest      | 3.11.1021                | twilightforest-1.12.2-3.11.1021-universal.jar | None                                     |
	| LCHIJA | tconstruct          | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar              | None                                     |
	| LCHIJA | galacticraftcore    | 4.0.2.280                | GalacticraftCore-1.12.2-4.0.2.280.jar         | None                                     |
	| LCHIJA | galacticraftplanets | 4.0.2.280                | Galacticraft-Planets-1.12.2-4.0.2.280.jar     | None                                     |
	| LCHIJA | asmodeuscore        | 0.0.25                   | AsmodeusCore-1.12.2-0.0.25.jar                | None                                     |
	| LCHIJA | bibliocraft         | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar             | None                                     |
	| LCHIJA | biomesoplenty       | 7.0.1.2417               | BiomesOPlenty-1.12.2-7.0.1.2417.jar           | None                                     |
	| LCHIJA | codechickenlib      | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | conarm              | 1.2.5.10                 | conarm-1.12.2-1.2.5.10.jar                    | b33d2c8df492beff56d1bbbc92da49b8ab7345a1 |
	| LCHIJA | culinaryconstruct   | 1.3.4                    | culinaryconstruct-1.3.4.jar                   | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LCHIJA | dimdoors            | 1.12.2-3.1.2+UNOFFICIAL  | DimensionalDoors-1.12.2-3.1.2-UNOFFICIAL.jar  | None                                     |
	| LCHIJA | enderstorage        | 2.4.6.137                | EnderStorage-1.12.2-2.4.6.137-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | foodexpansion       | 1.3                      | FoodExpansion1.3.3-1.12.2.jar                 | None                                     |
	| LCHIJA | gc-rpc              | 2.2.0                    | galacticraft-rpc-2.2.0.jar                    | None                                     |
	| LCHIJA | galaxyspace         | 2.0.16                   | GalaxySpace-1.12.2-2.0.16.jar                 | None                                     |
	| LCHIJA | geneticsreborn      | 1.09                     | Genetics-Reborn-Mod-1.12.2.jar                | None                                     |
	| LCHIJA | ichunutil           | 7.2.2                    | iChun-Util-Mod-1.12.2.jar                     | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | mjrlegendslib       | 1.12.2-1.2.0             | MJRLegendsLib-1.12.2-1.2.0.jar                | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCHIJA | stevekung's_lib     | 1.1.9                    | SteveKunG's-Lib-1.12.2-1.1.9.jar              | None                                     |
	| LCHIJA | moreplanets         | 2.2.1                    | More-Planets-1.12.2-2.2.1-GC280.jar           | None                                     |
	| LCHIJA | moreplanetsextras   | 1.12.2-1.0               | MorePlanetsExtras-1.12.2-1.0.jar              | None                                     |
	| LCHIJA | harvestcraft        | 1.12.2zb                 | Pam's+HarvestCraft+1.12.2zg.jar               | None                                     |
	| LCHIJA | srparasites         | 1.8.2                    | SRParasites-1.12.2v1.8.2.jar                  | None                                     |
	| LCHIJA | sync                | 7.1.0                    | Sync-Mod-1.12.2.jar                           | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | teamod              | 1.2.2                    | teamod-1.2.4-1.12.2.jar                       | None                                     |
	| LCHIJA | tinkersjei          | 1.2                      | tinkersjei-1.2.jar                            | None                                     |
	| LCHIJA | tinkertoolleveling  | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar           | None                                     |
	| LCHIJA | toughasnails        | 3.1.0.139                | ToughAsNails-1.12.2-3.1.0.139-universal.jar   | None                                     |
	| LCHIJA | vc                  | 5.9.16                   | ViesCraft-1.12.2-5.9.16.jar                   | None                                     |
	| LCHIJA | xaerominimap        | 21.4.4                   | Xaeros_Minimap_21.4.4_Forge_1.12.jar          | None                                     |
	| LCHIJA | gctweaks            | 1.6.0                    | GalacticTweaks-1.6.0.jar                      | 20692d890dcfa0d9cf061915fc32d00d1f295cbc |
	| LCHIJA | hungeroverhaul      | 1.12.2-1.3.3.jenkins148  | HungerOverhaul-1.12.2-1.3.3.jenkins148.jar    | None                                     |

	Loaded coremods (and transformers): 
GSHooksLoader (GalaxySpace-1.12.2-2.0.16.jar)
  galaxyspace.core.hooklib.minecraft.PrimaryClassTransformer
LoadingPlugin (replaymod-1.12.2-2.2.0-b7.jar)
  
SteveKunGLibPlugin (SteveKunG's-Lib-1.12.2-1.1.9.jar)
  
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
XaeroMinimapPlugin (Xaeros_Minimap_21.4.4_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
  xaero.common.core.transformer.EntityPlayerTransformer
  xaero.common.core.transformer.AbstractClientPlayerTransformer
  xaero.common.core.transformer.WorldClientTransformer
  xaero.common.core.transformer.EntityPlayerSPTransformer
  xaero.common.core.transformer.PlayerListTransformer
  xaero.common.core.transformer.GuiIngameForgeTransformer
  xaero.common.core.transformer.GuiBossOverlayTransformer
AppleCore (AppleCore-mc1.12.2-3.4.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 27.20.100.9466' Renderer: 'Intel(R) UHD Graphics 630'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	 

	################ [GALACTICTWEAKS DATA START] ################: 
	|	---------------------------------------------
	|	| GalaxySpace                        2.0.16 
	|	| --> AsmodeusCore                   0.0.25 
	|	| AsmodeusCore                       0.0.25 
	|	| MorePlanetsExtras              1.12.2-1.0 
	|	| Galacticraft Rich Presence                2.2.0 
	|	| More Planets                        2.2.1 
	|	| Galacticraft Planets            4.0.2.280 
	|	| Galacticraft Core               4.0.2.280 
	|	---------------------------------------------
	|	
	################# [GALACTICTWEAKS DATA END] #################

	Launched Version: 1.12.2-forge-14.23.5.2855
	LWJGL: 2.9.4
	OpenGL: Intel(R) UHD Graphics 630 GL version 4.6.0 - Build 27.20.100.9466, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz

**Comment by squeek502** [comment]
My guess would be an incompatibility with another core mod you have installed, but I'm not totally sure.
