### ISSUE TITLE
[1.7.10] Tooltip crash.

### ISSUE THREAD

**Issue by TerminalHash** [squeek502/AppleCore#158]
Hello!
It is very likely that the old version is no longer supported, but I still want to provide a report.

Stacktrace:
java.lang.NullPointerException: Unexpected error
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	**at squeek.applecore.client.TooltipOverlayHandler.onRenderTick(TooltipOverlayHandler.java:122)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_577_TooltipOverlayHandler_onRenderTick_RenderTickEvent.invoke(.dynamic)**
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onRenderTickEnd(FMLCommonHandler.java:340)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1003)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	
Steps to reproduce:
1. Open game.
2. Go to world (local, server).
3. Pickup any food.
4. Hover on this food cell.
5. ...
6. CRASH!

I using 3.1.1 version (also, infected and 3.1.0) (lastest on CurseForge). After removing this mod - game don't crash on tooltips.

**Comment by squeek502** [comment]
From where it's crashing, it looks like it might be related to NEI. Are you using NEI? If so, what version? If you remove NEI does the crash go away?

**Comment by TerminalHash** [comment]
In pack i using NEI 1.0.5.120, on older verison of pack (in 2017) this mod don't crash game.
And on the whole, NEI does not work. Now I will check without it.

UPD (15:51)
Everything works fine without NEI.

**Comment by squeek502** [comment]
Maybe try NEI version `1.0.5.118`?
