### ISSUE TITLE
Crash with Binnie's Mods

### ISSUE THREAD

**Issue by Maplenormandy** [squeek502/AppleCore#28]
Minecraft crashes when AppleCore attempts to look up the food value for liquids from Binnie's Mods, either when shift-clicking or when holding a container of the liquid. Not sure if this is AppleCore side or Binnie's Mods side, so I've posted bug reports to both.

```
---- Minecraft Crash Report ----
// My bad.

Time: 7/10/15 5:48 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at binnie.core.liquid.ItemFluidContainer.isDrinkable(ItemFluidContainer.java:180)
	at binnie.core.liquid.ItemFluidContainer.func_77661_b(ItemFluidContainer.java:151)
	at squeek.applecore.api_impl.AppleCoreAccessorMutatorImpl.isEdible(AppleCoreAccessorMutatorImpl.java:51)
	at squeek.applecore.api_impl.AppleCoreAccessorMutatorImpl.isFood(AppleCoreAccessorMutatorImpl.java:39)
	at squeek.applecore.client.TooltipOverlayHandler.onRenderTick(TooltipOverlayHandler.java:149)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_47_TooltipOverlayHandler_onRenderTick_RenderTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onRenderTickEnd(FMLCommonHandler.java:340)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1003)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at binnie.core.liquid.ItemFluidContainer.isDrinkable(ItemFluidContainer.java:180)
	at binnie.core.liquid.ItemFluidContainer.func_77661_b(ItemFluidContainer.java:151)
	at squeek.applecore.api_impl.AppleCoreAccessorMutatorImpl.isEdible(AppleCoreAccessorMutatorImpl.java:51)
	at squeek.applecore.api_impl.AppleCoreAccessorMutatorImpl.isFood(AppleCoreAccessorMutatorImpl.java:39)
	at squeek.applecore.client.TooltipOverlayHandler.onRenderTick(TooltipOverlayHandler.java:149)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_47_TooltipOverlayHandler_onRenderTick_RenderTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['maplenormandy'/185, l='MpServer', x=-260.50, y=67.62, z=179.50]]
	Chunk stats: MultiplayerChunkCache: 556, 556
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-256,64,172), Chunk: (at 0,4,12 in -16,10; contains blocks -256,0,160 to -241,255,175), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 326 game time, 326 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 104 total; [EntityZombie['Zombie'/1027, l='MpServer', x=-287.41, y=24.00, z=240.97], EntitySpider['Spider'/1028, l='MpServer', x=-338.28, y=30.00, z=176.94], EntitySkeleton['Skeleton'/1030, l='MpServer', x=-329.94, y=25.00, z=180.47], EntitySkeleton['Skeleton'/1060, l='MpServer', x=-294.50, y=50.00, z=143.88], EntitySkeleton['Skeleton'/1061, l='MpServer', x=-301.50, y=48.00, z=147.50], EntitySheep['Sheep'/61, l='MpServer', x=-334.50, y=69.00, z=107.50], EntitySheep['Sheep'/62, l='MpServer', x=-334.50, y=68.00, z=110.22], EntitySheep['Sheep'/63, l='MpServer', x=-334.50, y=69.00, z=111.81], EntityCow['Cow'/64, l='MpServer', x=-331.78, y=63.00, z=156.50], EntityCow['Cow'/65, l='MpServer', x=-330.19, y=63.00, z=156.50], EntityCow['Cow'/66, l='MpServer', x=-332.50, y=63.00, z=153.50], EntityCow['Cow'/67, l='MpServer', x=-333.50, y=63.00, z=155.50], EntityCow['Cow'/68, l='MpServer', x=-332.91, y=64.00, z=193.78], EntityCow['Cow'/69, l='MpServer', x=-329.50, y=64.00, z=193.75], EntityCow['Cow'/70, l='MpServer', x=-334.81, y=64.00, z=192.03], EntityCow['Cow'/71, l='MpServer', x=-334.81, y=64.00, z=193.66], EntityZombie['Zombie'/1097, l='MpServer', x=-196.50, y=27.00, z=244.50], EntityCow['Cow'/80, l='MpServer', x=-323.50, y=63.00, z=170.50], EntityCow['Cow'/81, l='MpServer', x=-325.50, y=63.00, z=170.50], EntityCow['Cow'/82, l='MpServer', x=-325.50, y=63.00, z=172.50], EntityCow['Cow'/83, l='MpServer', x=-325.50, y=63.00, z=170.50], EntityCow['Cow'/84, l='MpServer', x=-321.41, y=63.00, z=196.88], EntityCow['Cow'/85, l='MpServer', x=-320.03, y=63.00, z=198.81], EntityCow['Cow'/86, l='MpServer', x=-321.44, y=63.00, z=199.13], EntityCow['Cow'/87, l='MpServer', x=-323.31, y=63.00, z=197.19], EntitySheep['Sheep'/88, l='MpServer', x=-280.50, y=70.00, z=101.47], EntitySheep['Sheep'/89, l='MpServer', x=-280.50, y=70.00, z=102.81], EntitySheep['Sheep'/90, l='MpServer', x=-282.50, y=70.00, z=109.81], EntitySheep['Sheep'/91, l='MpServer', x=-284.50, y=71.00, z=102.50], EntitySheep['Sheep'/92, l='MpServer', x=-277.50, y=67.00, z=195.50], EntitySheep['Sheep'/93, l='MpServer', x=-274.05, y=68.00, z=187.69], EntitySheep['Sheep'/94, l='MpServer', x=-282.09, y=68.00, z=194.91], EntitySheep['Sheep'/95, l='MpServer', x=-280.19, y=68.00, z=190.22], EntitySheep['Sheep'/96, l='MpServer', x=-238.82, y=77.00, z=134.62], EntitySheep['Sheep'/97, l='MpServer', x=-233.50, y=72.00, z=140.22], EntitySheep['Sheep'/98, l='MpServer', x=-234.22, y=72.00, z=136.34], EntitySkeleton['Skeleton'/1122, l='MpServer', x=-283.50, y=28.00, z=221.50], EntitySheep['Sheep'/99, l='MpServer', x=-233.50, y=71.00, z=141.81], EntitySheep['Sheep'/100, l='MpServer', x=-249.47, y=67.00, z=167.34], EntitySheep['Sheep'/101, l='MpServer', x=-245.50, y=65.00, z=175.50], EntitySheep['Sheep'/102, l='MpServer', x=-248.44, y=65.00, z=173.59], EntitySheep['Sheep'/103, l='MpServer', x=-238.75, y=66.00, z=167.13], EntitySheep['Sheep'/104, l='MpServer', x=-248.13, y=66.00, z=187.06], EntitySheep['Sheep'/105, l='MpServer', x=-241.50, y=63.00, z=194.81], EntityCow['Cow'/106, l='MpServer', x=-248.09, y=63.00, z=240.09], EntityCow['Cow'/107, l='MpServer', x=-245.38, y=63.00, z=238.22], EntityCow['Cow'/108, l='MpServer', x=-246.94, y=63.00, z=238.94], EntityCow['Cow'/109, l='MpServer', x=-246.53, y=63.00, z=236.53], EntityCow['Cow'/110, l='MpServer', x=-216.50, y=65.00, z=252.50], EntityCow['Cow'/111, l='MpServer', x=-216.50, y=65.00, z=250.50], EntityCow['Cow'/112, l='MpServer', x=-217.19, y=64.00, z=245.84], EntityCow['Cow'/113, l='MpServer', x=-216.16, y=64.00, z=247.34], EntitySheep['Sheep'/126, l='MpServer', x=-193.50, y=69.00, z=112.50], EntitySheep['Sheep'/127, l='MpServer', x=-193.78, y=70.00, z=116.22], EntitySheep['Sheep'/128, l='MpServer', x=-189.50, y=70.00, z=116.50], EntitySheep['Sheep'/129, l='MpServer', x=-200.81, y=70.00, z=117.50], EntityCow['Cow'/130, l='MpServer', x=-192.50, y=63.00, z=224.50], EntityItem['item.tile.flower2.blueOrchid'/4235, l='MpServer', x=-321.78, y=64.13, z=144.28], EntityZombie['Zombie'/1172, l='MpServer', x=-315.50, y=24.00, z=197.50], EntityZombie['Zombie'/1173, l='MpServer', x=-316.50, y=24.00, z=196.50], EntitySkeleton['Skeleton'/1174, l='MpServer', x=-307.50, y=24.00, z=203.50], EntitySkeleton['Skeleton'/1175, l='MpServer', x=-308.50, y=24.00, z=203.50], EntitySkeleton['Skeleton'/1176, l='MpServer', x=-307.50, y=26.00, z=201.09], EntityZombie['Zombie'/1209, l='MpServer', x=-205.50, y=27.00, z=235.50], EntitySkeleton['Skeleton'/1210, l='MpServer', x=-208.47, y=26.00, z=228.94], EntityClientPlayerMP['maplenormandy'/185, l='MpServer', x=-260.50, y=67.62, z=179.50], EntityBat['Bat'/4294, l='MpServer', x=-316.44, y=25.89, z=196.28], EntityZombie['Zombie'/1226, l='MpServer', x=-323.50, y=15.00, z=166.50], EntityZombie['Zombie'/214, l='MpServer', x=-208.50, y=55.00, z=102.50], EntityZombie['Zombie'/215, l='MpServer', x=-206.50, y=55.00, z=101.50], EntityItem['item.tile.flower1.dandelion'/4312, l='MpServer', x=-311.22, y=64.13, z=149.59], EntityZombie['Zombie'/1250, l='MpServer', x=-317.50, y=28.00, z=122.50], EntitySkeleton['Skeleton'/1251, l='MpServer', x=-323.50, y=28.00, z=123.50], EntityItem['item.tile.flower1.dandelion'/4323, l='MpServer', x=-307.75, y=64.13, z=150.31], EntitySkeleton['Skeleton'/1252, l='MpServer', x=-324.50, y=28.00, z=122.50], EntityZombie['Zombie'/390, l='MpServer', x=-323.50, y=25.00, z=199.50], EntityBat['Bat'/415, l='MpServer', x=-224.41, y=31.45, z=181.22], EntityZombie['Zombie'/431, l='MpServer', x=-319.50, y=33.00, z=157.50], EntityBat['Bat'/456, l='MpServer', x=-340.82, y=44.66, z=173.12], EntityCreeper['Creeper'/1492, l='MpServer', x=-336.50, y=20.00, z=225.50], EntityZombie['Zombie'/1505, l='MpServer', x=-282.50, y=15.00, z=252.50], EntityCreeper['Creeper'/1506, l='MpServer', x=-286.50, y=15.00, z=253.50], EntitySkeleton['Skeleton'/1557, l='MpServer', x=-266.50, y=26.00, z=143.50], EntityBat['Bat'/560, l='MpServer', x=-330.44, y=22.77, z=203.25], EntityBat['Bat'/563, l='MpServer', x=-332.84, y=32.00, z=189.76], EntityBat['Bat'/578, l='MpServer', x=-313.28, y=26.39, z=197.75], EntityBat['Bat'/579, l='MpServer', x=-311.59, y=24.79, z=201.66], EntityZombie['Zombie'/670, l='MpServer', x=-224.50, y=12.00, z=183.50], EntitySkeleton['Skeleton'/672, l='MpServer', x=-224.50, y=12.00, z=181.50], EntityZombie['Zombie'/795, l='MpServer', x=-318.50, y=26.00, z=208.50], EntityZombie['Zombie'/796, l='MpServer', x=-317.88, y=25.00, z=206.44], EntityCreeper['Creeper'/797, l='MpServer', x=-322.50, y=26.00, z=206.50], EntitySkeleton['Skeleton'/806, l='MpServer', x=-322.50, y=22.00, z=187.50], EntitySkeleton['Skeleton'/807, l='MpServer', x=-318.50, y=23.00, z=192.69], EntitySkeleton['Skeleton'/847, l='MpServer', x=-218.16, y=24.00, z=237.41], EntitySkeleton['Skeleton'/848, l='MpServer', x=-222.50, y=25.00, z=240.09], EntitySkeleton['Skeleton'/849, l='MpServer', x=-219.16, y=24.00, z=236.66], EntityCreeper['Creeper'/875, l='MpServer', x=-275.50, y=14.00, z=120.50], EntitySkeleton['Skeleton'/898, l='MpServer', x=-198.50, y=19.00, z=105.50], EntitySkeleton['Skeleton'/909, l='MpServer', x=-306.50, y=18.00, z=160.50], EntityCreeper['Creeper'/955, l='MpServer', x=-225.50, y=12.00, z=179.50], EntityZombie['Zombie'/978, l='MpServer', x=-289.50, y=23.00, z=106.50], EntityZombie['Zombie'/981, l='MpServer', x=-286.50, y=23.00, z=104.50], EntitySkeleton['Skeleton'/1017, l='MpServer', x=-340.50, y=46.00, z=166.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_31, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 236307768 bytes (225 MB) / 640679936 bytes (611 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 19 mods loaded, 19 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10-universal.jar) 
	UCHIJAAAA	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10-universal.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.111} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.111-universal.jar) 
	UCHIJAAAA	AppleCore{1.1.0} [AppleCore] (AppleCore-mc1.7.10-1.1.0.jar) 
	UCHIJAAAA	Forestry{3.6.2.19} [Forestry for Minecraft] (forestry_1.7.10-3.6.2.19.jar) 
	UCHIJAAAA	BinnieCore{2.0-pre13} [Binnie Core] (binnie-mods-2.0-pre13.jar) 
	UCHIJAAAA	Botany{2.0-pre13} [Botany] (binnie-mods-2.0-pre13.jar) 
	UCHIJAAAA	ExtraBees{2.0-pre13} [Extra Bees] (binnie-mods-2.0-pre13.jar) 
	UCHIJAAAA	ExtraTrees{2.0-pre13} [Extra Trees] (binnie-mods-2.0-pre13.jar) 
	UCHIJAAAA	Genetics{2.0-pre13} [Genetics] (binnie-mods-2.0-pre13.jar) 
	UCHIJAAAA	NEIAddons{1.12.10.33} [NEI Addons] (neiaddons-1.12.10.33-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|AppEng{1.12.10.33} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.10.33-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Botany{1.12.10.33} [NEI Addons: Botany] (neiaddons-1.12.10.33-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Forestry{1.12.10.33} [NEI Addons: Forestry] (neiaddons-1.12.10.33-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|CraftingTables{1.12.10.33} [NEI Addons: Crafting Tables] (neiaddons-1.12.10.33-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|ExNihilo{1.12.10.33} [NEI Addons: Ex Nihilo] (neiaddons-1.12.10.33-mc1.7.10.jar) 
	UCHIJAAAA	neiintegration{1.0.11} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.11.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 353.30' Renderer: 'GeForce GT 730M/PCIe/SSE2'
	Launched Version: MultiMC5
	LWJGL: 2.9.1
	OpenGL: GeForce GT 730M/PCIe/SSE2 GL version 4.5.0 NVIDIA 353.30, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
```

**Comment by squeek502** [comment]
That'd be on Binnie's side. AppleCore is simply calling `Item.getItemUseAction()` with a valid ItemStack.
