### ISSUE TITLE
[1.7.10] NullPointerException in Applecore

### ISSUE THREAD

**Issue by Whimsyturtle** [squeek502/AppleCore#86]
{Reported on Behalf of slebreton}

AppleCore Version: 1.3.9 [MC 1.7.10] [Forge 10.13.4.1614]

Crash:
java.lang.NullPointerException: Unexpected error
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at squeek.applecore.client.TooltipOverlayHandler.onRenderTick(TooltipOverlayHandler.java:122)
at cpw.mods.fml.common.eventhandler.ASMEventHandler_974_TooltipOverlayHandler_onRenderTick_RenderTickEvent.invoke(.dynamic)
at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
at cpw.mods.fml.common.FMLCommonHandler.onRenderTickEnd(FMLCommonHandler.java:340)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1003)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by squeek502** [comment]
Need some more info. What version of NEI are you using (if you are using NEI)? If you are using NEI, does the crash still happen without NEI?

**Comment by frogkabobs** [comment]
I am having this same problem, though I am using heavily modded minecraft (200+ mods). I find that this seems to happen when holding shift over an empty slot. I am using AppleCore 3.1.1 [MC 1.7.10] [Forge 10.13.4.1614]. I have different, larger modpack with the same version of AppleCore where this issue does not occur, so I suspect that it is conflicting with another mod.

**Comment by frogkabobs** [comment]
I found the source of the issue. It appears that ThinkBigCore has been causing it. It is also worth noting that ThinkBigCore also causes the nei gui to disappear without a trace, so I believe this is the fault of ThinkBigCore rather than AppleCore.
